modes:
  clock:
    enable: true
    refresh: 1
  date:
    enable: true
    refresh: 5
  weather:
    enable: false
    refresh: 5
    update: 300
    provider: OWM
    unit: C
    location:
    api_key:
  exchange_rate:
    enable: false
    update: 300
    types:
      - from: EUR
        to: USD
  instagram:
    enable: false
    refresh: 5
    update: 300
    api_key:

brightness:
  mode: standard
  standard:
    default: 0
    increase_on_click: 1
    max: 15
  time_dependent:
    times:
      - from: '08:30'
        value: 2
      - from: '20:00'
        value: 0
